name: '📚 Documentation request'
description: Report something wrong or missing in the docs at ng-doc.com.
labels: ['Type: Documentation']
assignees: skoropadas

body:
  - type: input
    id: page
    attributes:
      label: Page
      description: A link to the page, or to the closest page if something is missing.
      placeholder: https://ng-doc.com/...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What's wrong or missing?
    validations:
      required: true
