import { logging } from '@angular-devkit/core';
import { SchematicTestRunner, UnitTestTree } from '@angular-devkit/schematics/testing';
import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { beforeEach, describe, expect, it } from 'vitest';

import { Schema } from '../schema';
import { budgetBytes } from '../steps/raise-initial-budget';
import { createRunner } from './ng-add-runner';

/** The Angular CLI's own schematics, which `ng new` runs. */
const angular: SchematicTestRunner = new SchematicTestRunner(
  '@schematics/angular',
  // The package exports map `./*` to `./*.js`, so Node resolves the collection through package.json.
  join(dirname(require.resolve('@schematics/angular/package.json')), 'collection.json'),
);

/** The Vite engine's dependencies, as the builder package declares them. */
const VITE_DEPENDENCIES: Record<string, string> = JSON.parse(
  readFileSync(join(__dirname, '../../../../builder/package.json'), 'utf8'),
).peerDependencies;

interface AppOptions {
  ssr?: boolean;
  zoneless?: boolean;
  standalone?: boolean;
}

/**
 * An application as `ng new docs` of Angular 22 creates it (the workspace root is the project).
 * @param options - The `ng new` options; SSR, zoneless and standalone by default.
 */
async function newApp(options: AppOptions = {}): Promise<UnitTestTree> {
  const { ssr = true, zoneless = true, standalone = true } = options;
  const workspace: UnitTestTree = await angular.runSchematic('workspace', {
    name: 'docs',
    newProjectRoot: 'projects',
    version: '22.0.6',
  });

  return angular.runSchematic(
    'application',
    { name: 'docs', projectRoot: '', ssr, zoneless, standalone, skipInstall: true },
    workspace,
  );
}

/**
 * Every file of a tree with its content. `runSchematic` changes the tree it is given, so take the
 * snapshot before a run.
 * @param tree - The tree.
 */
function files(tree: UnitTestTree): Record<string, string> {
  return Object.fromEntries(tree.files.map((file: string) => [file, tree.readContent(file)]));
}

/** A target of `angular.json`, as far as the specs read it. */
interface Target {
  builder: string;
  options: Record<string, unknown>;
}

/**
 * The targets of the `docs` project.
 * @param tree - The tree.
 */
function architect(tree: UnitTestTree): Record<string, Target> {
  return JSON.parse(tree.readContent('angular.json')).projects.docs.architect;
}

describe('ng-add with the Vite engine', () => {
  let runner: SchematicTestRunner;
  let logs: logging.LogEntry[];

  const logged = (level?: string): string =>
    logs
      .filter((entry: logging.LogEntry) => !level || entry.level === level)
      .map((entry: logging.LogEntry) => entry.message)
      .join('\n');
  const setup = (tree: UnitTestTree, options: Partial<Schema> = {}): Promise<UnitTestTree> =>
    runner.runSchematic('ng-add-setup-project', { project: '', ...options }, tree);

  beforeEach(() => {
    runner = createRunner();
    logs = [];
    runner.logger.subscribe((entry: logging.LogEntry) => logs.push(entry));
  });

  it('should set up a new SSR application with the Vite builders', async () => {
    const tree: UnitTestTree = await setup(await newApp());
    const targets: Record<string, Target> = architect(tree);

    expect(targets['build']).toEqual({
      builder: '@ng-doc/builder:vite-application',
      options: { configFile: 'vite.config.mjs', outputPath: 'dist/docs' },
      configurations: { production: { mode: 'production' }, development: { mode: 'development' } },
      defaultConfiguration: 'production',
    });
    expect(targets['serve']).toEqual({
      builder: '@ng-doc/builder:vite-dev-server',
      options: { configFile: 'vite.config.mjs' },
      configurations: { production: { mode: 'production' }, development: { mode: 'development' } },
      defaultConfiguration: 'development',
    });
    // The Angular build options stay for the unit-test builder, which reads them.
    expect(targets['build-angular'].builder).toBe('@angular/build:application');
    expect(targets['build-angular'].options['styles']).toEqual([
      'node_modules/@ng-doc/app/styles/global.css',
      'node_modules/@ng-doc/app/styles/themes/dark.css',
      'src/styles.css',
    ]);
    expect(targets['test'].options).toEqual({ buildTarget: 'docs:build-angular:development' });
    expect(Object.keys(targets)).toEqual(['build', 'build-angular', 'serve', 'test']);
  });

  it('should describe the application in vite.config.mjs', async () => {
    const tree: UnitTestTree = await setup(await newApp());
    const config: string = tree.readContent('vite.config.mjs');

    expect(config).toContain('generated by `ng add @ng-doc/add`');
    expect(config).toContain("browser: 'src/main.ts'");
    expect(config).toContain("server: 'src/main.server.ts'");
    // The dark theme is loaded, so the theme toggle's Dark option switches the site to it.
    expect(config.replace(/\s+/g, ' ')).toContain(
      "styles: [ 'node_modules/@ng-doc/app/styles/global.css', 'node_modules/@ng-doc/app/styles/themes/dark.css', 'src/styles.css', ]",
    );
    expect(config).toContain("input: 'node_modules/@ng-doc/ui-kit/assets'");
    expect(config).toContain("input: 'public'");
    // The Vite plugin serves the generated assets itself.
    expect(config).not.toContain("input: 'ng-doc/docs/assets'");
    expect(config).toContain("angularComponentProbe: workspace('src/app/app.ts')");
    expect(config).toContain("projectId: 'docs'");
    expect(config).toContain("outputRoot: workspace('ng-doc/docs')");
    expect(config).not.toContain('polyfills');
  });

  it('should wrap the server entry, ignore the cache and add the Vite dependencies', async () => {
    const tree: UnitTestTree = await setup(await newApp());
    const manifest = JSON.parse(tree.readContent('package.json'));

    expect(tree.readContent('src/main.server.ts')).toContain(
      "import { withNgDocContentReady } from '@ng-doc/app/helpers';",
    );
    expect(tree.readContent('src/main.server.ts')).toContain(
      'export default withNgDocContentReady(bootstrap);',
    );
    expect(tree.readContent('.gitignore')).toMatch(/\n\/ng-doc\n[\s\S]*\n\/\.cache\/ng-doc\n/);
    expect(manifest.devDependencies['vite']).toBe(VITE_DEPENDENCIES['vite']);
    expect(manifest.devDependencies['@analogjs/vite-plugin-angular']).toBe(
      VITE_DEPENDENCIES['@analogjs/vite-plugin-angular'],
    );
    // `ng add` installs them with the NgDoc packages: the setup schedules no install of its own.
    expect(runner.tasks).toEqual([]);
  });

  it('should add the providers and the layout, and report what the Vite engine does not build', async () => {
    const tree: UnitTestTree = await setup(await newApp());
    const config: string = tree.readContent('src/app/app.config.ts');

    expect(config).toContain('provideRouter([...routes, ...NG_DOC_ROUTING]');
    expect(config).toContain('provideNgDocContext()');
    expect(config).not.toContain('ChangeDetection');
    expect(tree.readContent('src/app/app.ts')).toContain('NgDocRootComponent');
    expect(logged('info')).toContain('Engine: Vite');
    expect(logged('warn')).toContain('`build.outputMode`');
    expect(logged('warn')).toContain('`build.ssr.entry`');
    expect(logged('warn')).not.toContain('legacy');
    expect(logged('info')).toMatch(/does not use: [^\n]*`build\.budgets`/);
    // The Vite engine has no budgets: the kept Angular options are not changed.
    expect(architect(tree)['build-angular']).not.toHaveProperty(
      'configurations.production.budgets.0.maximumError',
      '5mb',
    );
    // The NgDoc asset entries are kept; only the generated one is left to the Vite plugin.
    expect(logged('info')).not.toMatch(/does not use: [^\n]*`build\.assets`/);
  });

  it('should set up a client-side application with zone.js', async () => {
    const tree: UnitTestTree = await setup(await newApp({ ssr: false, zoneless: false }));
    const config: string = tree.readContent('vite.config.mjs');

    expect(architect(tree)['build'].builder).toBe('@ng-doc/builder:vite-application');
    expect(config).toContain("polyfills: ['zone.js']");
    expect(config).not.toContain('server:');
    expect(tree.exists('src/main.server.ts')).toBe(false);
    expect(tree.readContent('src/app/app.config.ts')).toContain('provideZoneChangeDetection');
    expect(logged('warn')).toBe('');
  });

  it('should change nothing on a second run', async () => {
    const first: UnitTestTree = await setup(await newApp());
    const before: Record<string, string> = files(first);
    const second: UnitTestTree = await setup(first);

    expect(files(second)).toEqual(before);
    expect(logged()).toContain('already builds with the Vite engine');
  });

  it('should set up the legacy builders with --engine legacy', async () => {
    const tree: UnitTestTree = await setup(await newApp(), { engine: 'legacy' });
    const targets: Record<string, Target> = architect(tree);

    expect(targets['build'].builder).toBe('@ng-doc/builder:application');
    expect(targets['serve'].builder).toBe('@ng-doc/builder:dev-server');
    expect(targets['build-angular']).toBeUndefined();
    expect(tree.exists('vite.config.mjs')).toBe(false);
    expect(tree.readContent('src/main.server.ts')).not.toContain('withNgDocContentReady');
    expect(JSON.parse(tree.readContent('package.json')).devDependencies['vite']).toBeUndefined();
    expect(logged('info')).toContain('Engine: legacy');
    // `ng new` allows 1 MB; the legacy build of the NgDoc runtime alone is larger.
    expect(
      JSON.parse(tree.readContent('angular.json')).projects.docs.architect.build.configurations
        .production.budgets,
    ).toEqual([
      { type: 'initial', maximumWarning: '500kB', maximumError: '5mb' },
      { type: 'anyComponentStyle', maximumWarning: '4kB', maximumError: '8kB' },
    ]);

    const legacyFiles: Record<string, string> = files(tree);
    const again: UnitTestTree = await setup(tree, { engine: 'legacy' });

    expect(files(again)).toEqual(legacyFiles);
  });

  it('should keep a project on the legacy builders and point to migrate-to-vite', async () => {
    const legacy: UnitTestTree = await setup(await newApp(), { engine: 'legacy' });
    const before: Record<string, string> = files(legacy);

    logs = [];
    const again: UnitTestTree = await setup(legacy);

    expect(files(again)).toEqual(before);
    expect(logged('info')).toContain('ng g @ng-doc/builder:migrate-to-vite');

    logs = [];
    const requested: UnitTestTree = await setup(legacy, { engine: 'vite' });

    expect(files(requested)).toEqual(before);
    expect(logged('warn')).toContain('"--engine vite" was ignored');
  });

  it('should keep an NgDoc builder that is not the legacy one', async () => {
    const app: UnitTestTree = await newApp();
    const workspace = JSON.parse(app.readContent('angular.json'));

    workspace.projects.docs.architect.build.builder = '@ng-doc/builder:modern-application';
    app.overwrite('angular.json', JSON.stringify(workspace, null, 2));

    const tree: UnitTestTree = await setup(app);

    expect(architect(tree)['build'].builder).toBe('@ng-doc/builder:modern-application');
    expect(architect(tree)['serve'].builder).toBe('@ng-doc/builder:dev-server');
    expect(tree.exists('vite.config.mjs')).toBe(false);
  });

  it('should keep the Vite engine when --engine legacy is passed to a Vite project', async () => {
    const first: UnitTestTree = await setup(await newApp());
    const before: Record<string, string> = files(first);
    const second: UnitTestTree = await setup(first, { engine: 'legacy' });

    expect(files(second)).toEqual(before);
    expect(logged('warn')).toContain('"--engine legacy" was ignored');
  });

  it('should give an NgModule application the legacy builders', async () => {
    const tree: UnitTestTree = await setup(await newApp({ standalone: false }));

    expect(architect(tree)['build'].builder).toBe('@ng-doc/builder:application');
    expect(tree.exists('vite.config.mjs')).toBe(false);
    expect(logged('info')).toContain('bootstraps an NgModule');
  });

  it('should refuse the Vite engine for an NgModule application', async () => {
    await expect(setup(await newApp({ standalone: false }), { engine: 'vite' })).rejects.toThrow(
      /NGDOC_ADD_ENGINE[\s\S]*--engine legacy/,
    );
  });

  it('should refuse a project that the Vite engine cannot build, as migrate-to-vite does', async () => {
    const app: UnitTestTree = await newApp();
    const workspace = JSON.parse(app.readContent('angular.json'));

    workspace.projects.docs.architect.build.options.localize = ['de'];
    app.overwrite('angular.json', JSON.stringify(workspace, null, 2));

    await expect(setup(app)).rejects.toThrow(
      /NGDOC_VITE_SETUP_BLOCKED[\s\S]*build\.localize[\s\S]*--engine legacy/,
    );
  });

  it('should refuse a custom builder and an existing vite.config.mjs', async () => {
    const custom: UnitTestTree = await newApp();
    const workspace = JSON.parse(custom.readContent('angular.json'));

    workspace.projects.docs.architect.build.builder =
      '@angular-builders/custom-esbuild:application';
    custom.overwrite('angular.json', JSON.stringify(workspace, null, 2));

    await expect(setup(custom, { engine: 'vite' })).rejects.toThrow(
      /`build`: uses `@angular-builders\/custom-esbuild/,
    );

    const existing: UnitTestTree = await newApp();

    existing.create('vite.config.mjs', 'export default {};\n');

    await expect(setup(existing)).rejects.toThrow(/`vite\.config\.mjs`: already exists/);
  });

  it('should read budget sizes as the Angular CLI does', () => {
    expect(budgetBytes('1MB')).toBe(1024 ** 2);
    expect(budgetBytes('500kB')).toBe(500 * 1024);
    expect(budgetBytes('5mb')).toBe(5 * 1024 ** 2);
    expect(budgetBytes('2048')).toBe(2048);
    expect(budgetBytes('10%')).toBeUndefined();
  });

  it('should give an application on another builder the legacy builders unless --engine vite is passed', async () => {
    const appWith = async (builder: string): Promise<UnitTestTree> => {
      const app: UnitTestTree = await newApp();
      const workspace = JSON.parse(app.readContent('angular.json'));

      workspace.projects.docs.architect.build.builder = builder;
      app.overwrite('angular.json', JSON.stringify(workspace, null, 2));

      return app;
    };

    for (const builder of ['@nx/angular:application', '@angular-devkit/build-angular:browser']) {
      logs = [];

      const tree: UnitTestTree = await setup(await appWith(builder));

      expect(architect(tree)['build'].builder).toBe('@ng-doc/builder:application');
      expect(tree.exists('vite.config.mjs')).toBe(false);
      expect(logged('info')).toContain(`"build" target uses "${builder}"`);
      await expect(setup(await appWith(builder), { engine: 'vite' })).rejects.toThrow(
        /NGDOC_VITE_SETUP_BLOCKED/,
      );
    }
  });

  it('should keep build and serve of a project whose NgDoc builder is on another target', async () => {
    const app: UnitTestTree = await newApp();
    const workspace = JSON.parse(app.readContent('angular.json'));

    workspace.projects.docs.architect['docs'] = { builder: '@ng-doc/builder:application' };
    app.overwrite('angular.json', JSON.stringify(workspace, null, 2));

    const tree: UnitTestTree = await setup(app);

    expect(architect(tree)['build'].builder).toBe('@angular/build:application');
    expect(architect(tree)['serve'].builder).toBe('@angular/build:dev-server');
    expect(tree.exists('vite.config.mjs')).toBe(false);
    expect(logged('info')).toContain('"docs" runs @ng-doc/builder:application');
  });

  it('should raise only the ng new budget of a project new to NgDoc', async () => {
    // An existing legacy project with the `ng new` budget keeps it.
    const existing: UnitTestTree = await setup(await newApp(), { engine: 'legacy' });
    const workspace = JSON.parse(existing.readContent('angular.json'));
    const budgets = workspace.projects.docs.architect.build.configurations.production.budgets;

    budgets[0].maximumError = '1MB';
    existing.overwrite('angular.json', JSON.stringify(workspace, null, 2));

    const before: Record<string, string> = files(existing);
    const again: UnitTestTree = await setup(existing);

    expect(files(again)).toEqual(before);

    // A budget the project chose itself is kept.
    const custom: UnitTestTree = await newApp();
    const customWorkspace = JSON.parse(custom.readContent('angular.json'));

    customWorkspace.projects.docs.architect.build.configurations.production.budgets[0].maximumError =
      '2mb';
    custom.overwrite('angular.json', JSON.stringify(customWorkspace, null, 2));

    const tree: UnitTestTree = await setup(custom, { engine: 'legacy' });

    expect(
      JSON.parse(tree.readContent('angular.json')).projects.docs.architect.build.configurations
        .production.budgets[0].maximumError,
    ).toBe('2mb');
  });

  it('should read the build options of build-legacy after migrate-to-vite', async () => {
    const legacy: UnitTestTree = await setup(await newApp(), { engine: 'legacy' });
    const workspace = JSON.parse(legacy.readContent('angular.json'));
    const targets = workspace.projects.docs.architect;

    // The targets as migrate-to-vite leaves them.
    targets['build-legacy'] = targets.build;
    targets.build = {
      builder: '@ng-doc/builder:vite-application',
      options: { configFile: 'vite.config.mjs', outputPath: 'dist/docs' },
    };
    legacy.overwrite('angular.json', JSON.stringify(workspace, null, 2));
    logs = [];

    const before: Record<string, string> = files(legacy);
    const tree: UnitTestTree = await setup(legacy);

    expect(files(tree)).toEqual(before);
    expect(logged('error')).toBe('');
    expect(logged('info')).toContain('NgDoc App configuration');
  });
});
