name: NgDoc action for Node.js
description: Setup Node.js

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: npm

    - name: Cache NPM dependencies
      uses: actions/cache@v3
      id: cache-npm-dependencies
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache-npm-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
