name: ⚙️ Build

on:
    workflow_call:
        inputs:
            base:
                type: string
                description: Base branch
                required: false
                default: 'remotes/origin/main'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup Node.js
                uses: ./.github/actions/nodejs

            -   name: Build
                run: npx nx affected --target=build --parallel --base=${{ inputs.base }}
