name: ⚙️ Build

on:
  workflow_call:
    inputs:
      base:
        type: string
        description: Base branch
        required: false
        default: 'main'
      head:
        type: string
        description: Head branch
        required: false
        default: 'HEAD'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: git fetch origin ${{ inputs.base }}

      - name: Setup Node.js
        uses: ./.github/actions/nodejs

      - name: Build Libraries
        run: npx nx run-many --projects=tag:type:lib --target=build --parallel

      - name: Build Applications
        run: npx nx run-many --projects=tag:type:app --target=build --parallel
