name: 📦 Create Beta Release

on: workflow_dispatch

jobs:
  merge-release:
    name: Merge release into beta
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE }}
          source: 'release'
          target: 'beta'
  merge-main:
    name: Merge main into beta
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE }}
          source: 'main'
          target: 'beta'
