name: 📦 Create Release

on: workflow_dispatch

jobs:
  merge-main:
    name: Merge main into release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE }}
          source: 'main'
          target: 'release'
