name: ⚙️ Lint

on:
    workflow_call:
        inputs:
            base:
                type: string
                description: Base branch
                required: false
                default: 'remotes/origin/main'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup Node.js
                uses: ./.github/actions/nodejs

            -   name: Lint
                run: npx nx affected --target=lint --quiet=true --parallel -- --base=${{ inputs.base }}
