name: Tests

on: workflow_call

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  cache: npm
                  node-version: 18

            - name: Install Dependencies
              run: npm ci

            - name: Test
              run: npx nx run-many --all --target=test --configuration=ci
